export const en = {
  lang: "en",
  htmlLang: "en",
  siteTitle: "Manchester City Website",
  siteDescription: "A multilingual introduction website for Manchester City Football Club",
  brand: "MANCHESTER CITY",
  navHome: "Home",
  navSquad: "Squad",
  navHonours: "Honours",
  navApi: "API",
  heroBadge: "Hono + Cloudflare Workers",
  heroTitle: "Manchester City Web App",
  heroDesc:
    "This is a real web application, not just a static page. It supports multilingual routes, JSON APIs, and can be extended into news, fixtures, player details, and an admin system.",
  btnSquad: "View Squad",
  btnApi: "Open JSON API",
  sectionFeatures: "Project Features",
  sectionFeaturesDesc: "Compared with a single index.html file, this project is much closer to a production website.",
  feature1Title: "Multilingual Routing",
  feature1Desc: "Supports /zh, /en and /es paths, which is better for SEO and future expansion.",
  feature2Title: "Server-side Rendering",
  feature2Desc: "Uses Hono to render HTML directly on Workers, making it fast and clean.",
  feature3Title: "JSON API",
  feature3Desc: "Provides structured data via /api/club?lang=xx, reusable by frontend or mobile apps.",
  factsTitle: "Club Facts",
  founded: "Founded",
  stadium: "Stadium",
  colors: "Colors",
  league: "League",
  squadTitle: "First Team Core Squad",
  squadDesc: "This page demonstrates an independent route. Later it can grow into player profiles, stats pages, and transfer pages.",
  squadCardDesc: "Example player card. Later you can connect it to a database or external API for numbers, positions, photos, and statistics.",
  honoursTitle: "Major Honours",
  honoursDesc: "This page demonstrates another route and is a good base for filtering, searching, and admin features.",
  honoursList: [
    "English top-flight titles: 10",
    "FA Cup titles: 7",
    "League Cup titles: 8",
    "UEFA Champions League titles: 1",
    "UEFA Super Cup titles: 1",
    "FIFA Club World Cup titles: 1"
  ],
  statLeague: "League Titles",
  statFaCup: "FA Cups",
  statLeagueCup: "League Cups",
  footer: "This is a multilingual website example built with Hono + Cloudflare Workers."
}
