export const es = {
  lang: "es",
  htmlLang: "es",
  siteTitle: "Sitio Web del Manchester City",
  siteDescription: "Un sitio web multilingue de presentación del Manchester City Football Club",
  brand: "MANCHESTER CITY",
  navHome: "Inicio",
  navSquad: "Plantilla",
  navHonours: "Titulos",
  navApi: "API",
  heroBadge: "Hono + Cloudflare Workers",
  heroTitle: "Aplicacion web del Manchester City",
  heroDesc:
    "Esta es una aplicacion web real, no solo una pagina estatica. Soporta rutas multilingues, API JSON y puede ampliarse con noticias, partidos, perfiles de jugadores y panel de administracion.",
  btnSquad: "Ver plantilla",
  btnApi: "Abrir API JSON",
  sectionFeatures: "Caracteristicas del proyecto",
  sectionFeaturesDesc: "En comparacion con un solo archivo index.html, este proyecto se parece mucho mas a un sitio web real en produccion.",
  feature1Title: "Rutas multilingues",
  feature1Desc: "Soporta las rutas /zh, /en y /es, lo que ayuda al SEO y a futuras ampliaciones.",
  feature2Title: "Renderizado del lado del servidor",
  feature2Desc: "Usa Hono para generar HTML directamente en Workers, con buena velocidad y estructura clara.",
  feature3Title: "API JSON",
  feature3Desc: "Ofrece datos estructurados mediante /api/club?lang=xx, reutilizables por frontend o apps moviles.",
  factsTitle: "Datos del club",
  founded: "Fundacion",
  stadium: "Estadio",
  colors: "Colores",
  league: "Liga",
  squadTitle: "Plantilla principal",
  squadDesc: "Esta pagina demuestra una ruta independiente. Mas adelante puede crecer con perfiles de jugadores, estadisticas y fichajes.",
  squadCardDesc: "Tarjeta de jugador de ejemplo. Mas adelante puedes conectarla a una base de datos o API externa para mostrar dorsal, posicion, fotos y estadisticas.",
  honoursTitle: "Titulos principales",
  honoursDesc: "Esta pagina demuestra otra ruta y sirve como base para filtros, busqueda y administracion.",
  honoursList: [
    "Titulos de la maxima categoria inglesa: 10",
    "FA Cup: 7",
    "League Cup: 8",
    "Liga de Campeones de la UEFA: 1",
    "Supercopa de la UEFA: 1",
    "Mundial de Clubes de la FIFA: 1"
  ],
  statLeague: "Ligas",
  statFaCup: "FA Cups",
  statLeagueCup: "League Cups",
  footer: "Este es un ejemplo de sitio web multilingue creado con Hono + Cloudflare Workers."
}
