export const zh = {
  lang: "zh",
  htmlLang: "zh-CN",
  siteTitle: "曼城足球网站",
  siteDescription: "曼城足球俱乐部多语言介绍网站",
  brand: "MANCHESTER CITY",
  navHome: "首页",
  navSquad: "阵容",
  navHonours: "荣誉",
  navApi: "接口",
  heroBadge: "Hono + Cloudflare Workers",
  heroTitle: "曼城足球网站程序",
  heroDesc:
    "这是一个真正的网站程序，不是纯静态页。它支持多语言页面路由、JSON API，并且可以继续扩展为新闻、赛程、球员详情和后台管理系统。",
  btnSquad: "查看阵容页",
  btnApi: "打开 JSON API",
  sectionFeatures: "项目特点",
  sectionFeaturesDesc: "相较于单个 index.html，这个项目更接近真实上线网站的结构。",
  feature1Title: "多语言路由",
  feature1Desc: "支持 /zh、/en、/es 三种语言路径，适合 SEO 和后续扩展。",
  feature2Title: "服务端渲染",
  feature2Desc: "通过 Hono 在 Worker 侧直接输出 HTML 页面，速度快，结构清晰。",
  feature3Title: "JSON API",
  feature3Desc: "通过 /api/club?lang=xx 提供结构化数据，前端或移动端都能复用。",
  factsTitle: "俱乐部信息",
  founded: "成立时间",
  stadium: "主场",
  colors: "主色",
  league: "联赛",
  squadTitle: "一线队核心阵容",
  squadDesc: "这里演示独立页面路由。后续可以扩展成球员详情页、数据页和转会页。",
  squadCardDesc: "示例球员卡片。后续可接数据库或外部 API，显示号码、位置、照片和统计数据。",
  honoursTitle: "主要荣誉",
  honoursDesc: "这里演示另一条页面路由，也方便后面做筛选、搜索和管理功能。",
  honoursList: [
    "英格兰顶级联赛冠军：10次",
    "足总杯冠军：7次",
    "联赛杯冠军：8次",
    "欧冠冠军：1次",
    "欧洲超级杯冠军：1次",
    "世俱杯冠军：1次"
  ],
  statLeague: "联赛冠军",
  statFaCup: "足总杯",
  statLeagueCup: "联赛杯",
  footer: "这是一个基于 Hono + Cloudflare Workers 的多语言网站程序示例。"
}
